<title>Cab.vn Mobile</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta charset="utf-8">
<meta property="fb:app_id" content="235095629949087">
<meta property="fb:admins" content="100001996385091">
<!--        <link rel="stylesheet" type="text/css" href="/css/mobile/custom.css">-->


<link rel="stylesheet" type="text/css" href="/css/admin/style.css" />
<!-- <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>-->