<div id="header" >
    <div id="header-wrap" >
        <a href='/' id="logo"><span><img src="/images/logo.png" /></span></a> 
        <div class="verticle-span"></div>
        <form action='/search' id="search-form">
            <p>
                <input type='text' placeholder="Từ khóa" autocomplete="off" id='search-box'/>
            </p>
        </form>
        <div id="menu">
            <div id="menu-button"></div>
        </div>
        
    </div>
</div>
<section data-type="sidebar" role="region" id="subMenu">
<nav>
    <h2>Thông tin tài khoản</h2>
    <ul>
        <li><a href="#content">Trang cá nhân</a></li>
        <li><a href="#content">Thay đổi thông tin và mật khẩu</a></li>
     
        <li><a href="#content">Đăng xuất</a></li>
    </ul>
                    <h2>Subtitle</h2>
                    <ul>
                        <li><a href="#content">label</a></li>
                        <li><a href="#content">label</a></li>
                        <li><a href="#content">label larger label than the </a></li>
                        <li><a href="#content">label</a></li>
                    </ul>
</nav>
</section>
