<div id="header" >
    <div id="header-wrap" >
        <a href='/' id="logo"><span><img src="/images/logo.png" style='margin-top: 10px;'/></span></a> 
        
<!--        <form action='/search' id="search-form">
            <p>
                <input type='text' placeholder="Từ khóa" autocomplete="off" id='search-box'/>
            </p>
        </form>-->
        <div id="menu">
            <a href="/">Trang chủ</a>
            <a href="/user/logout" style="">Đăng xuất</a>
        </div>
        
    </div>
</div>
<section data-type="sidebar" role="region" id="subMenu">
</section>
