<div id="header" >
        <button><span class="icon icon-back"></span></button>
        <menu type="toolbar">
            <button id='menu'><span class="icon icon-menu"></span></button>
        </menu>
        <form action='/search' id="search-form">
            <p>
                <input type='text' placeholder="Từ khóa" autocomplete="off" id='search-box'/>
                <button type='reset'>Remove text</button>   
            </p>
        </form>
        <h2 id="logo"><a href='/'><img src="/images/logo.png" /></a></h2>   

</div>
<!--<section data-type="sidebar" role="region" id="subMenu">
<nav>
    <h2>Thông tin tài khoản</h2>
    <ul>
        <li><a href="#content">Trang cá nhân</a></li>
        <li><a href="#content">Thay đổi thông tin</a></li>
        <li><a href="#content">Thay đổi mật khẩu</a></li>
        <li><a href="#content">Đăng xuất</a></li>
    </ul>
                    <h2>Subtitle</h2>
                    <ul>
                        <li><a href="#content">label</a></li>
                        <li><a href="#content">label</a></li>
                        <li><a href="#content">label larger label than the </a></li>
                        <li><a href="#content">label</a></li>
                    </ul>
</nav>
</section>-->
