<?php
if (count($this->message) > 0) {
    echo "<section rol='info'>
        <span class='close'></span>";
    foreach ($this->message as $ms) {
        echo $ms . "<br/>";
    }
    echo "</section>";
}
if ($this->status){
    echo "<section rol='info'>
        <span class='close'></span> Đã cập nhật thành công</section>";
}
    echo $this->form;
echo "<a href='/admin/news/'><< Trở về trang trước</a>";