<?php
$this->headTitle("Ảnh mới");
echo "<input type='hidden' id='page_id' value='" . $this->page . "' />";
$message = $this->message;
if ($message['error'] != null)
    echo "Error " . $message['error'];

$news = $this->news;
foreach ($news as $n) {
    ?>
    <div class='news'>
        <span class='close'></span>
        <div><?php echo html_entity_decode($n->title); ?></div> <a href='/news/index/id/<?php echo $n->id ?>'>xem tiếp>></a> 
    </div>
    <?php
}
if ($message['content']) {
    foreach ($message['content'] as $i => $info) {
        $relative_time = $message['relative_time'][$i];
        $like_status = $message['like_status'][$i];
        ?>
        <section class="post-item" >
            <a href='<?= "/c/" . $info['pid'] ?>' class='post-image' target='_blank'>
                <?php
                if ($info['type'] == "photo")
                    echo "<img src='/photos/medium/" . $info['name'] . "' width='100%' />";
                else
                    echo "<img src='http://img.youtube.com/vi/" . $info['name'] . "/0.jpg' width='100%' class='post-video'/> 
                            <div class='video-indicator'></div>";
                ?>
            </a>
            <section class='post-info post-position-absolute' data-type="list">
                <header>
                    <?= stripcslashes($info['title']) ?> 
                </header>
                <ul>
                    <li>
                        <aside class="icon">
                            <a href="/uploader/<?php echo $info['uid'] ?>" ><img src="/photos/avatar/<?= $info['avatar'] ?> " alt="<?php echo $info['username'] ?>"/></a>
                        </aside>
                        <a href="http://cnweb/c/<?= $info['pid'] ?>" >

                            <p>
                                <input type='hidden' class='id' value='<?php echo $info['pid'] ?>' like-status='<?php echo $like_status; ?>' />
                                <span class='post-like'><?= $info['num_like'] ?></span> &nbsp; &nbsp;
                                <span class='post-comment'><?= $info['comment'] ?></span> &nbsp; &nbsp;
                                <span class="fb-like" data-href="http://cnweb/c/<?= $info['pid'] ?>/" data-send="false" data-layout="button_count" data-width="60" data-show-faces="false"></span>

                            </p>
                            <p>
                                <?= $relative_time ?> bởi <?php echo "<span class='link' href='/uploader/" . $info['uid'] . "'> <strong>" . $info['username'] . "</strong></span>"; ?>

                            </p>
                        </a>

                    </li>
                </ul>

            </section>

        </section>
        <?
    }
}
if (!count($message['content']))
    echo "<h2>Không còn bài nào cũ hơn</h2>
                                Trở về <a href='/'><strong>Trang chủ</a>";
?>