<title>Cab.vn Mobile</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta property="fb:app_id" content="235095629949087" />
<meta property="fb:admins" content="100001996385091"/>
<!--        <link rel="stylesheet" type="text/css" href="/css/mobile/custom.css">-->

<link rel="stylesheet" type="text/css" href="/css/jquery.mobile.min.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/drawer.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/lists.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/tabs.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/toolbars.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/headers.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/switches.css" />

<link rel="stylesheet" type="text/css" href="/css/mobile/input_areas.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/buttons.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/time_selector.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/lists.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/buttons.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/date_selector.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/value_selector.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/edit_mode.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/building_block.css">
<link rel="stylesheet" type="text/css" href="/css/mobile/progress_activity.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/status.css" />
<link rel="stylesheet" type="text/css" href="/css/mobile/style.css">
<script type="text/javascript" >
    var windowWidth = window.innerWidth;
</script>