<div id="toolbar-wrap">
    <div role="toolbar" id="toolbar">

        <ul>
            <li><button class="pack-icon-send" id="send-message">Send</button></li>
            <li><button class="pack-icon-mark" id="like">Like</button></li>
            <li><div class='hozirontal-span'></div><li>
            <li><button class="pack-icon-share" id='facebook-share'>Share</button></li>
        </ul>
    </div>
</div>