<div id="plugin-content-cover"></div>
<div id='plugin-message'>
    <div id='plugin-message-content'></div>
    <h2 class="bb-docs">&nbsp;</h2>
    <form method="post" role="search" onsubmit="cab.sendMessage();
            return false;">
        <button type="submit" > Bình luận</button>
        <p>
            <input type="text" id='plugin-msg'>
            <button type="reset">Clear</button>
        </p>

    </form>

</div>
<div id='plugin-facebook'>

</div>
