<script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/js/enscroll-0.4.0.min.js"></script>
<!--<script type="text/javascript" src="/js/jquery.mobile-1.3.1.min.js"></script>-->
<!--        <script type="text/javascript" src="/js/mobile/app.js"></script>-->
<!--<script type="text/javascript" src="/js/effect.js"></script>-->
<script type="text/javascript" id="cab-script" src="/js/cab.js<?php if ($this->mode) echo "?".$this->mode ?>"></script>
<!--<script type='text/javascript' src='/js/effect.js'></script>-->

<?php
if ($this->scroll_script_include)
    echo '<script type="text/javascript" src="/js/cab.scroll.js"></script>'
?>
<script type="text/javascript" src="/js/jquery.fitvids.js"></script>
<script type="text/javascript" src="/js/cab.youtube.js"></script>
<!--<script type="text/javascript" src="/js/jquery-ui.min.js"></script>-->
<!--<script type="text/javascript" src="/js/wp-ui.js"></script>-->