<script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
<!--        <script type="text/javascript" src="/js/mobile/app.js"></script>-->
<!--<script type="text/javascript" src="/js/effect.js"></script>-->
<script type="text/javascript" src="/js/cab.js"></script>
<script type="text/javascript" src="/js/cab.scroll.js"></script>
<!--<script type="text/javascript" src="/js/jquery-ui.min.js"></script>-->
<!--<script type="text/javascript" src="/js/wp-ui.js"></script>-->