<h1> Hot</h1>
<?php
$this->headTitle("Ảnh mới");

$message = $this->message;
if ($message['error'] != null)
    echo "Error " . $message['error'];

if ($message['content']) {
    foreach ($message['content'] as $info) {
        ?>
        <div class="post-item">
            <a href='<?= "/c/".$info['pid']?>' class='post-image' target='_blank'>
                <img src='/photos/<?=$info['name']?>' width="100%" />
            </a>
            <div class='post-info'>
                <div><a href='<?= "/c/".$info['pid'] ?>'><h3><?= $info['title'] ?></h3></a></div>
                 <div>Likes <?= $info['like'] ?></div>s
            </div>
        </div>
        <?
    }
}
?>