<h1> Hot</h1>
<?php
$this->headTitle("Ảnh mới");

$message = $this->message;
if ($message['error'] != null)
    echo "Error " . $message['error'];

if ($message['content']) {
    foreach ($message['content'] as $info) {
        ?>
        <section class="post-item">
            <a href='<?= "/c/" . $info['pid'] ?>' class='post-image' target='_blank'>
                <img src='/photos/<?= $info['name'] ?>' width="100%" />
            </a>
            <section class='post-info'>
                <div><a href='<?= "/c/" . $info['pid'] ?>'><h3><?= $info['title'] ?></h3></a></div>
                <div class='post-like'><?= $info['like'] ?></div>
                <div class="fb-like" data-href="http://cnweb/c/<?=$info['pid'] ?>/" data-send="true" data-width="250" data-show-faces="true"></div>
            </section>
        </section>
        <?
    }
}
?>