<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->partial('mobile/head.phtml'); ?>
    </head>
    <body role="application">

        <?php
        require 'mobile/menu.phtml';
        ?>

        <section id="suggest-container" data-type="list">
        </section>
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>

        <?php
        require_once 'mobile/nav.phtml';
        require_once 'plugins/facebook.phtml';  
        echo "<div id='plugin-content'>";
        require_once 'mobile/chat_test.phtml';
        echo  "</div>";
        require_once 'mobile/script.phtml';
        ?>
    </body>
</html>