<!DOCTYPE html>
<html>
    <head>
        <title>Cab.vn Mobile</title>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <!--        <link rel="stylesheet" type="text/css" href="/css/mobile/custom.css">-->
        <link rel="stylesheet" type="text/css" href="/css/mobile/s.css">
        <link rel="stylesheet" type="text/css" href="/css/mobile/building_block.css">

        <link rel="stylesheet" type="text/css" href="/css/mobile/drawer.css">
        <link rel="stylesheet" type="text/css" href="/css/mobile/lists.css">
        <link rel="stylesheet" type="text/css" href="/css/mobile/tabs.css">
        <link rel="stylesheet" type="text/css" href="/css/mobile/toolbars.css">
        <link rel="stylesheet" type="text/css" href="/css/mobile/headers.css">
        <link rel="stylesheet" type="text/css" href="/css/mobile/switches.css" />
        <link rel="stylesheet" type="text/css" href="/css/mobile/style.css">

    </head>
    <body role="application">

        <section role="region" class="skin-organic">
            <header>
                <button><span class="icon icon-back"></span></button>
                <menu type="toolbar">
                    <button id='menu'><span class="icon icon-menu"></span></button>
                </menu>
                <form action='/search' id="search-form">
                    <input type='text' placeholder="Từ khóa" autocomplete="off" id='search-box'/>
                    <button type='reset'>Remove text</button>
                </form>
                <h2 id="logo"><img src="/images/logo.png" /></h2>
            </header>
     
        </section>
        <section data-type="sidebar" role="region" id="menu-sub">
            <nav>
                <h2>Thông tin tài khoản</h2>
                <ul>
                    <li><a href="#content">Trang cá nhân</a></li>
                    <li><a href="#content">Thay đổi thông tin</a></li>
                    <li><a href="#content">Thay đổi mật khẩu</a></li>
                    <li><a href="#content">Đăng xuất</a></li>
                </ul>
<!--                <h2>Subtitle</h2>
                <ul>
                    <li><a href="#content">label</a></li>
                    <li><a href="#content">label</a></li>
                    <li><a href="#content">label larger label than the </a></li>
                    <li><a href="#content">label</a></li>
                </ul>-->
            </nav>
        </section>
        <section id="content">
            
        </section>
        <script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
<!--        <script type="text/javascript" src="/js/mobile/app.js"></script>-->
        <script type="text/javascript" src="/js/effect.js"></script>
        <script type="text/javascript" src="/js/cab.js"></script>
    </body>
</html>